services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3000}
        INTERNAL_API_URL: http://backend:4000/api
        INTERNAL_BACKEND_URL: http://backend:4000

    environment:
      INTERNAL_API_URL: http://backend:4000/api
      INTERNAL_BACKEND_URL: http://backend:4000

    ports:
      - '3000:3000'

    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile

    env_file:
      - ./apps/backend/.env

    ports:
      - '4000:4000'